### ISSUE TITLE
Composer issues

### ISSUE THREAD

**Issue by samparmenter** [scharrier/li3_socialauth#2]
I am no expert on using composer but I ran into an issue using composer with your li3 plugin. I have no idea why it is happening but when you run composer update it pulls down your repository perfectly but when it pulls in the external lib (oauth lib from Lusitanian) it fails to get "dev-master". It works if you change the composer.json in your project to read:

"require":{
    "lusitanian/oauth": "0.1.*@dev"
}

I don't know enough about composer to say why because if we look at the composer file in lusitanian/oauth we can see an alias of "dev-master": "0.1-dev" which I assumed would work.

**Comment by scharrier** [comment]
It works for me, I don't know Composer enough, maybe you have a specific Composer configuration or an old version ? 

Here is the result of "composer update" for me :
Loading composer repositories with package information
Updating dependencies
- Installing lusitanian/oauth (dev-master 082e105)
  Cloning 082e105d01f3490efdfd5e3d1c7ebf2c078d3c69

Give me more details on your environment and the error you had in order I can try to reproduce please :)
Writing lock file
Generating autoload files

**Comment by samparmenter** [comment]
Hmm, thanks for the fast reply!

I have literally just started using composer and pulled it from the site earlier today so I doubt its an issue with composer itself. I am on OSX mountain lion if that helps.

What is the require line you have in your composer.json for lusitanian/oauth btw, is it

"require":{
    "lusitanian/oauth": "dev-master"
}

**Comment by scharrier** [comment]
I have reproduced. Everything works fine if you clone my git repo, but if you include it in a project as a composer dependancy, it fails.

I don't have any idea actually, I have to test it more. I'll do that this evening, sorry.

**Comment by samparmenter** [comment]
Lovely, thanks for the replies and I look forward to having a play with your plugin today!

Thanks

Sam

**Comment by scharrier** [comment]
I removed the "dev-master" and got back to "*". Seems to work.

I close, reopen if you still have issues. Give me feedback on my email if it works (or not) ! ;)

**Comment by samparmenter** [comment]
Works a treat! Thanks very much.
