### ISSUE TITLE
Install without composer

### ISSUE THREAD

**Issue by minhna** [scharrier/li3_socialauth#6]
Hi,
Is there another way to load add this awesome library without using composer?

Thank you.
Minh

**Comment by scharrier** [comment]
Hi,

You have to do 3 things :
- first, git clone li3_socialauth in your libraries directory
- load it with the Li3 Libraries::add() method
- use a PSR-0 compliant autoloader to let the dependencies load (like this : https://gist.github.com/jwage/221634 )

If it work, I let you close this Issue. Ask help if needed :)

**Comment by minhna** [comment]
It's too complicated for me. I will stick with composer.
Let's close this one.
Thank you very much.
